# Generated by Django 4.2 on 2023-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cofee', 'Coffee'), ('Tea', 'Tee'), ('Juice', 'Juice')], max_length=100, verbose_name='Drink Type')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=25, verbose_name='Drink Size')),
            ],
        ),
    ]
