# Generated by Django 4.2 on 2023-04-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('Ice Cofee', 'Icecoffee'), ('Black Cofee', 'Blackcoffee'), ('Capuccino', 'Capuccino'), ('Black Tea', 'Blacktea'), ('Green Tea', 'Greentea'), ('English Tea', 'Englishtea'), ('Orange Juice', 'Orangejuice'), ('Apple Juice', 'Applejuice'), ('Mango Juice', 'Mangojuice')], max_length=100, verbose_name='Drink Type'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.drink')),
            ],
        ),
    ]
